function createfigure(cdata1, titlestr)
%CREATEFIGURE(CDATA1)
%  CDATA1:  image cdata

%  Auto-generated by MATLAB on 17-Nov-2014 11:00:46

% Create figure
figure1 = figure;

[y, x] = size(cdata1);

% Create axes
axes1 = axes('Parent',figure1,'YDir','reverse','Layer','top');
% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[.5 x+.5]);
% Uncomment the following line to preserve the Y-limits of the axes
 ylim(axes1,[.5 y+.5]);
box(axes1,'on');
hold(axes1,'all');

colormap(jet(256));

%scaled = (mag2db(cdata1)+70)/70*255;

% Create image
%image(scaled,'Parent',axes1,'CDataMapping','direct');
image(cdata1,'Parent',axes1,'CDataMapping','scaled');

%truesize();

% Create xlabel
xlabel('Bin of Mel Spectrum');

% Create ylabel
ylabel('Frame of Audio');

% Create title
title(titlestr);

% Create colorbar
%colorbar('peer',axes1);

